INSERT INTO products
(name, category, price, description, image_url, created_by, updated_by) VALUES

('WMX Gym Gloves','Gloves',499,'Comfortable grip gloves for intense workout training','/images/wmx_gloves.jpg','admin','admin'),
('Spike Gym Gloves','Gloves',459,'Strong padded gloves for heavy weight lifting','/images/spike_gloves.jpg','admin','admin'),
('Kobo Gym Gloves','Gloves',479,'Durable gloves designed for professional gym users','/images/kobo_gloves.jpg','admin','admin'),
('De Jure Gym Gloves','Gloves',499,'Soft breathable gloves for daily gym exercises','/images/de_jure_gloves.jpg','admin','admin'),
('RDX Gym Gloves','Gloves',549,'Premium quality gloves for powerful training sessions','/images/rdx_gloves.jpg','admin','admin'),
('Hyks Gym Gloves','Gloves',439,'Flexible gloves providing better grip and comfort','/images/hyks_gloves.jpg','admin','admin'),
('Super Grip Gloves','Gloves',499,'Anti slip gloves for maximum hand protection','/images/super_grip_gloves.jpg','admin','admin'),
('Nivia Gym Gloves','Gloves',429,'Lightweight gloves suitable for beginner workouts','/images/nivia_gloves.jpg','admin','admin'),
('Cofit Gym Gloves','Gloves',459,'Breathable gloves ideal for cardio and strength training','/images/cofit_gloves.jpg','admin','admin'),

('Milton Gym Bottle','Bottles',299,'Leak proof water bottle for gym hydration','/images/milton_bottle.jpg','admin','admin'),
('Boldfit Gym Bottle','Bottles',349,'High quality bottle for workout water storage','/images/boldfit_bottle.jpg','admin','admin'),
('Sports N Gym Bottle','Bottles',279,'Durable bottle for daily fitness hydration','/images/sportsn_bottle.jpg','admin','admin'),
('Pringle Gym Bottle','Bottles',319,'Stylish bottle designed for active gym users','/images/pringle_bottle.jpg','admin','admin'),
('Pawahy Gym Bottle','Bottles',259,'Compact bottle for easy carrying during workouts','/images/pawahy_bottle.jpg','admin','admin'),
('Werfit Gym Bottle','Bottles',299,'Strong plastic bottle for regular training sessions','/images/werfit_bottle.jpg','admin','admin'),
('Pexpo Gym Bottle','Bottles',329,'Modern design bottle for fitness hydration needs','/images/pexpo_bottle.jpg','admin','admin'),

('MuscleBlaze Gym Bag','Bags',1299,'Spacious gym bag with multiple storage compartments','/images/muscleblaze_bag.jpg','admin','admin'),
('Spike Gym Bag','Bags',1199,'Lightweight gym bag for daily workout essentials','/images/spike_bag.jpg','admin','admin'),
('Cureveda Gym Bag','Bags',1099,'Stylish gym bag suitable for fitness accessories','/images/cureveda_bag.jpg','admin','admin'),
('Nabaat Gym Bag','Bags',1149,'Compact gym bag for carrying workout gear','/images/nabaat_bag.jpg','admin','admin'),
('GNC Gym Bag','Bags',1399,'Premium branded gym bag with durable build','/images/gnc_bag.jpg','admin','admin'),
('Nike Gym Bag','Bags',1899,'High quality sports gym bag for professionals','/images/nike_bag.jpg','admin','admin'),
('Boldfit Gym Bag','Bags',1249,'Modern gym bag with strong shoulder straps','/images/boldfit_bag.jpg','admin','admin'),

('Nutrabay Preworkout','Preworkout',1599,'Energy boosting supplement for intense gym workouts','/images/nutrabay_preworkout.jpg','admin','admin'),
('Optimum Preworkout','Preworkout',1699,'Advanced preworkout powder for high performance','/images/optimum_preworkout.jpg','admin','admin'),
('Wellversed Preworkout','Preworkout',1499,'Plant based preworkout for natural energy boost','/images/wellversed_preworkout.jpg','admin','admin'),
('Maxn Preworkout','Preworkout',1399,'High strength preworkout for powerful gym sessions','/images/maxn_preworkout.jpg','admin','admin'),
('Outwork Nutrition Preworkout','Preworkout',1599,'Performance focused supplement for workout endurance','/images/outwork_preworkout.jpg','admin','admin'),
('NoStorm Preworkout','Preworkout',1449,'Fast acting preworkout for muscle pump','/images/nostorm_preworkout.jpg','admin','admin'),
('Gold Standard Preworkout','Preworkout',1799,'Premium preworkout supporting extreme workout intensity','/images/goldstandard_preworkout.jpg','admin','admin'),
('Six Star Preworkout','Preworkout',1399,'Reliable preworkout for sustained workout energy','/images/sixstar_preworkout.jpg','admin','admin'),
('MuscleBlaze Preworkout','Preworkout',1499,'Professional preworkout enhancing workout performance','/images/muscleblaze_preworkout.jpg','admin','admin'),

('Neulife Creatine','Creatine',1299,'Pure creatine supplement supporting muscle growth','/images/neulife_creatine.png','admin','admin'),
('Selfom Nutrition Creatine','Creatine',1399,'High quality creatine for strength improvement','/images/selfom_creatine.png','admin','admin'),
('BigMuscles Creatine','Creatine',1499,'Advanced creatine powder for bodybuilding support','/images/bigmuscles_creatine.webp','admin','admin'),
('Goldsport Creatine','Creatine',1199,'Reliable creatine for daily muscle training','/images/goldsport_creatine.avif','admin','admin'),
('MuscleTech Creatine','Creatine',1699,'Premium creatine for professional muscle development','/images/muscletech_creatine.webp','admin','admin'),
('Wellversed Creatine','Creatine',1399,'Plant based creatine for clean muscle energy','/images/wellversed_creatine.webp','admin','admin'),
('ON Creatine','Creatine',1799,'High purity creatine for strength performance','/images/on_creatine.jpg','admin','admin'),
('MuscleBlaze Creatine','Creatine',1599,'Pure micronized creatine for fast absorption','/images/muscleblaze_creatine.webp','admin','admin'),

('MyPro Whey','Whey',2599,'High protein whey powder for muscle recovery','/images/mypro_whey.avif','admin','admin'),
('IsoMatrix Whey','Whey',2799,'Isolate whey protein for lean muscle building','/images/isomatrix_whey.webp','admin','admin'),
('Dymatize Whey','Whey',3199,'Premium whey protein for faster muscle recovery','/images/dymatize_whey.webp','admin','admin'),
('GNC Whey','Whey',2999,'High quality whey protein for daily workouts','/images/gnc_whey.webp','admin','admin'),
('Gold Whey','Whey',2899,'Classic whey protein supporting muscle growth','/images/gold_whey.jpg','admin','admin'),
('ON Nutrition Whey','Whey',3299,'Trusted whey protein for professional fitness','/images/onnutrition_whey.webp','admin','admin'),
('MuscleBlaze Whey','Whey',2699,'Popular whey protein for muscle building support','/images/muscleblaze_whey.webp','admin','admin');
