CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,

    name VARCHAR(100) NOT NULL,

    username VARCHAR(150) NOT NULL UNIQUE,   -- email / login id
    password VARCHAR(255) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(50)
);

CREATE TABLE addresses (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL UNIQUE,
    door_no VARCHAR(50) NOT NULL,
    street VARCHAR(150) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    pincode VARCHAR(10) NOT NULL,



    created_at DATETIME,
    updated_at DATETIME,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),

    CONSTRAINT fk_address_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);CREATE TABLE roles (
      ROLE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,

      ROLE_NAME VARCHAR(50) NOT NULL,

      USER_ID BIGINT NOT NULL,

      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CREATED_BY VARCHAR(50),

      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UPDATED_BY VARCHAR(50),

      CONSTRAINT fk_role_user
          FOREIGN KEY (USER_ID)
          REFERENCES users(id)
          ON DELETE CASCADE
  );
);
CREATE TABLE user_memberships (
    USER_MEMBERSHIP_ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    USER_ID BIGINT NOT NULL,
    USER_EMAIL VARCHAR(150),

    MEMBERSHIP_ID BIGINT NOT NULL,
    PLAN_NAME VARCHAR(100),
    PLAN_MONTHS INT,
    PLAN_PRICE INT,
    USER_PAID_PRICE INT,

    START_DATE DATE,
    END_DATE DATE,

    STATUS VARCHAR(20),   -- ACTIVE / EXPIRED

    PURCHASED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),

    FOREIGN KEY (USER_ID) REFERENCES users(id),
    FOREIGN KEY (MEMBERSHIP_ID) REFERENCES membership_details(MEMBERSHIP_ID)
);
CREATE TABLE orders (
    ORDER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    USER_ID BIGINT NOT NULL,
    USER_EMAIL VARCHAR(150),

    TOTAL_AMOUNT INT,
    PAYMENT_STATUS VARCHAR(20),  -- PAID / FAILED / REFUNDED

    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),

    FOREIGN KEY (USER_ID) REFERENCES users(id)
);
CREATE TABLE order_items (
    ORDER_ITEM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,

    PRODUCT_NAME VARCHAR(150),
    PRODUCT_PRICE INT,
    QUANTITY INT,
    SUB_TOTAL INT,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),

    FOREIGN KEY (ORDER_ID) REFERENCES orders(ORDER_ID)
);
CREATE TABLE contact_messages (
    CONTACT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    USER_ID BIGINT NOT NULL,
    USER_EMAIL VARCHAR(150),

    SUBJECT VARCHAR(150),
    MESSAGE TEXT,

    STATUS VARCHAR(20),   -- SENT / ACCEPTED / REJECTED

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    FOREIGN KEY (USER_ID) REFERENCES users(id)
);
